// <auto-generated />
namespace Kuzey.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class a1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a1));
        
        string IMigrationMetadata.Id
        {
            get { return "201901020710217_a1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
