// <auto-generated />
namespace EF_CF1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class urunlertablosueklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urunlertablosueklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "201812271024113_urunlertablosueklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
