// <auto-generated />
namespace Otel.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class computed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(computed));
        
        string IMigrationMetadata.Id
        {
            get { return "201901040612382_computed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
